# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        TOKEN: ${{ secrets.private_config }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install disnake
        python -m pip install requests
        echo $TOKEN | tee ./src/private-config.json
    - name: GitHub Actions job_id parser
      uses: Tiryoh/gha-jobid-action@v0.1.2
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: ${{ github.job }}

    - name: Output Current Job Log URL
      run: echo ${{ steps.jobs.outputs.html_url }} | tee ./src/actions_job_id.txt
    - name: Host The Bot
      run: |
        
        cd src
        ls
        echo Hosting Bot
        python main.py ${{ github.sha }} "${{ github.event.commits[0].message }}" "${{ secrets.GITHUB_TOKEN }}" ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID} "${{ github.repository }}"
        echo Bot Killed
        echo Stopping Action

