# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        TOKEN: ${{ secrets.private_config }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install disnake
        echo $TOKEN | tee ./src/private-config.json
    - name: Get Current Job Log URL
      run:
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT}/jobs | jq .jobs[].id
    - name: Host The Bot
      run: |
        
        cd src
        ls
        echo Hosting Bot
        python main.py ${{ github.sha }} "${{ github.event.commits[0].message }}"
        echo Bot Killed
        echo Stopping Action

